### PR TITLE
Forgot to translate sealable aluminium wire

### PR DESCRIPTION
**Pull request by mMONTAGEe**

### CODE REVIEW

**Comment by mMONTAGEe** [comment]
30 Day anniversary 🎉

**Review by JoeZwet — CHANGES_REQUESTED** [review]
we had this pull request independently reviewed and they came back with quite a few notes.

Miss translations, grammar and spelling mistakes, missing capital letters etc.

**Comment by mMONTAGEe** [comment]
> we had this pull request independently reviewed and they came back with quite a few notes.
> 
> Miss translations, grammar and spelling mistakes, missing capital letters etc.

Can i contact that guy? i wanna he guide me where i made mistakes

**Comment by JoeZwet** [comment]
Sorry I can't do that but I can give you this list of issues.

https://haste.romvoid.dev/qudufidiju.yml

**Comment by mMONTAGEe** [comment]
> Sorry I can't do that but I can give you this list of issues.
> 
> https://haste.romvoid.dev/qudufidiju.yml

Fk my grammar is dying.
But i doubt that Space Race was translated wrong

**Comment by vos6434** [comment]
having a friend review this

**Comment by mMONTAGEe** [comment]
do not reopen. Please

**Pull request closed without merging**
