### PR TITLE
feat: add Galacticraft 4 music as discs

### PR DESCRIPTION
**Pull request by JoeZwet**
PR for #47

TODO:
* ~~Find original music artist name.~~
* ~~Get proper textures to music discs (currently using Strad disc texture)~~
* ~~Add discs to loot tables~~

### CODE REVIEW

**Comment by marcus8448** [comment]
I believe the original artist's name is Jackson Cordes. (According to https://micdoodle8.com/mods/galacticraft)

**Comment by vos6434** [comment]
test comment

**Comment by vos6434** [comment]
test comment

**Comment by vos6434** [comment]
test comment

**Review by marcus8448 — APPROVED** [review]

**Pull request merged**
